<?php

########################################################################
# Extension Manager/Repository config file for ext: "ajadomaps"
#
# Auto generated by Extension Builder 2012-04-19
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Ajado maps',
	'description' => 'An extension for administrating and displaying custom maps, like branches of a company.',
	'category' => 'plugin',
	'author' => 'Stephan Petzl',
	'author_email' => 'stephan.petzl@ajado.com',
	'author_company' => 'Ajado',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>